### ISSUE TITLE
vcio2-0.1 fails to build on 4.14.89-v7+

### ISSUE THREAD

**Issue by ast** [maazl/vc4asm#24]
```bash
sudo make
cat /var/lib/dkms/vcio2/0.1/build/make.log
```

```bash
DKMS make.log for vcio2-0.1 for kernel 4.14.89-v7+ (armv7l)
Mon Dec 31 13:06:04 CET 2018
make[1]: Entering directory '/var/lib/dkms/vcio2/0.1/build/src'
make -C /lib/modules/4.14.89-v7+/build M=/var/lib/dkms/vcio2/0.1/build
make[2]: Entering directory '/var/lib/dkms/vcio2/0.1/build/src'
make[2]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
  AR      /var/lib/dkms/vcio2/0.1/build/built-in.o
  CC [M]  /var/lib/dkms/vcio2/0.1/build/src/vcio2.o
/var/lib/dkms/vcio2/0.1/build/src/vcio2.c:42:24: fatal error: mach/vcio2.h: No such file or directory
 #include <mach/vcio2.h>
                        ^
compilation terminated.
scripts/Makefile.build:332: recipe for target '/var/lib/dkms/vcio2/0.1/build/src/vcio2.o' failed
make[3]: *** [/var/lib/dkms/vcio2/0.1/build/src/vcio2.o] Error 1
Makefile:1532: recipe for target '_module_/var/lib/dkms/vcio2/0.1/build' failed
make[2]: *** [_module_/var/lib/dkms/vcio2/0.1/build] Error 2
make[2]: Leaving directory '/home/pi/linux-af369f47021f11e78017c0a98e55cb934b501c36'
Makefile:5: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/var/lib/dkms/vcio2/0.1/build/src'
```

**Comment by maazl** [comment]
Hi Albin,

unfortunately, vcio2 is discontinued and there is probably no way to 
reactivate it. I should mention this on my site.

The new vc4 driver currently accesses the GPU /exclusively/, so no user 
code can access the GPU anymore when vc4 is running. I still would 
prefer a solution where user shader code can run without disabling the 
graphics driver completely.

So you are stuck with accessing the vc4 device directly and run all 
applications as root as the hello_pi examples do. Of course this will 
crash if more than one application tries to access the GPU concurrently. 
And you must not enable the vc4 driver in the config.


Marcel

Am 31.12.18 um 13:08 schrieb Albin Stigo:
> sudo make
> cat /var/lib/dkms/vcio2/0.1/build/make.log
[...]

**Comment by ast** [comment]
What a shame, so much wasted potential! Thanks for replying so quickly!

**Comment by maazl** [comment]
vcio2 is back again!
I found a way to get it working on newer kernels.
=> [vcio2](https://github.com/maazl/vcio2)

Of course it still may conflict with vc4 but at least for default installation up to the Raspberry Pi 3 models it should work.
